In [1]:
import pandas as pd

In [2]:
def make_table(taxon_id, number_rows=10):
    df = pd.read_csv(f'./results/{taxon_id}/{taxon_id}_network_analysis.csv')
    df.fillna('-', inplace=True)
    df.rename(
        columns={
            'name': 'gene name',
            'MCODE::Clusters (1)': 'MCODE cluster',
            'AverageShortestPathLength': 'average shortest path length',
            'ClusteringCoefficient': 'cluster coefficient',
            'ClosenessCentrality':'closeness centrality',
        },
        inplace=True
    )
    df.sort_values(by='average shortest path length', ascending=True, inplace=True)
    df = df.round(2)
    return df[['gene name', 'MCODE cluster', 'average shortest path length', 'cluster coefficient', 'closeness centrality']].head(number_rows)

- Enterococcus faecalis (strain ATCC 700802 / V583) / taxon id 226185

In [3]:
taxon_id = 226185
make_table(taxon_id)

,gene name,MCODE cluster,average shortest path length,cluster coefficient,closeness centrality
12,vanB,Cluster 0,1.22,0.50,0.82
6,murC,Cluster 0,1.30,0.63,0.77
19,rpoB,Cluster 0,1.33,0.59,0.75
13,pbpC,Cluster 0,1.37,0.65,0.73
8,mraY,Cluster 0,1.37,0.67,0.73
24,EF_0680,Cluster 0,1.37,0.68,0.73
26,EF_1740,Cluster 0,1.41,0.72,0.71
25,EF_1148,Cluster 0,1.41,0.72,0.71
9,uppS,Cluster 0,1.44,0.64,0.69
10,murB,Cluster 0,1.44,0.79,0.69

- Staphylococcus aureus (strain NCTC 8325 / PS 47)/ taxon id 93061

In [7]:
taxon_id = 93061
make_table(taxon_id)

,gene name,MCODE cluster,average shortest path length,cluster coefficient,closeness centrality
20,murF,Cluster 0,1.34,0.56,0.75
34,murE,Cluster 0,1.34,0.52,0.75
30,mprF,Cluster 2,1.34,0.39,0.75
27,ddl,Cluster 0,1.39,0.56,0.72
15,murB,Cluster 1,1.39,0.66,0.72
32,recA,Cluster 1,1.42,0.52,0.70
10,murC,Cluster 0,1.42,0.65,0.70
12,mraY,Cluster 0,1.45,0.63,0.69
29,murG,Cluster 1,1.45,0.64,0.69
13,ABD30180.1,Cluster 0,1.45,0.58,0.69

- Escherichia coli (strain K12) / taxon id 83333

In [5]:
taxon_id = 83333
make_table(taxon_id)

,gene name,MCODE cluster,average shortest path length,cluster coefficient,closeness centrality
39,gyrA,Cluster 0,1.43,0.39,0.70
38,parE,Cluster 0,1.52,0.46,0.66
40,gyrB,Cluster 0,1.53,0.48,0.65
14,rpoB,Cluster 0,1.54,0.56,0.65
23,rpsL,Cluster 0,1.54,0.58,0.65
43,macB,Cluster 1,1.54,0.38,0.65
37,parC,Cluster 0,1.56,0.49,0.64
1,arnA,Cluster 1,1.57,0.36,0.64
19,rpsD,Cluster 0,1.58,0.59,0.63
52,tolC,Cluster 1,1.58,0.44,0.63

- Klebsiella pneumoniae subsp. pneumoniae (strain ATCC 700721 / MGH 78578) / taxon id 272620

In [6]:
taxon_id=272620
make_table(taxon_id)

,gene name,MCODE cluster,average shortest path length,cluster coefficient,closeness centrality
4,galE,-,1.62,0.38,0.62
1,mrcB,Cluster 1,1.66,0.43,0.60
3,ybgF,Cluster 3,1.66,0.40,0.60
17,yfbH,Cluster 0,1.66,0.44,0.60
0,murG,Cluster 3,1.72,0.47,0.58
8,wbaP,Cluster 0,1.72,0.44,0.58
9,pbpG,Cluster 2,1.72,0.47,0.58
10,uppP,Cluster 1,1.72,0.45,0.58
26,arnF,Cluster 0,1.75,0.53,0.57
24,yfbG,Cluster 0,1.75,0.60,0.57