In [2]:
import pandas as pd

In [20]:
def make_table(taxon_id, number_rows=10):
    df = pd.read_csv(f'./results/{taxon_id}/{taxon_id}_network_analysis.csv')
    df.fillna('-', inplace=True)
    df.rename(
        columns={
            'name': 'gene name',
            'MCODE::Clusters (1)': 'MCODE cluster',
            'AverageShortestPathLength': 'average shortest path length',
            'ClusteringCoefficient': 'cluster coefficient',
            'ClosenessCentrality':'closeness centrality',
        },
        inplace=True
    )
    df.sort_values(by='average shortest path length', ascending=False, inplace=True)
    df = df.round(2)
    return df[['gene name', 'MCODE cluster', 'average shortest path length', 'cluster coefficient', 'closeness centrality']].head(number_rows)

- Enterococcus faecalis (strain ATCC 700802 / V583) / taxon id 226185

In [19]:
taxon_id = 226185
make_table(taxon_id)

,gene name,MCODE cluster,average shortest path length,cluster coefficient,closeness centrality
11,gelE,-,1.93,0.50,0.52
3,dgkA,Cluster 2,1.93,0.80,0.52
0,vanHB,Cluster 1,1.78,0.76,0.56
15,EF_0485,-,1.78,0.76,0.56
1,vanW,Cluster 1,1.78,0.90,0.56
23,EF_0796,Cluster 2,1.74,0.54,0.57
22,EF_1261,Cluster 1,1.70,0.60,0.59
4,vanX,Cluster 1,1.67,0.61,0.60
17,dltA,-,1.67,0.47,0.60
27,mprF,-,1.59,0.51,0.63

- Staphylococcus aureus (strain NCTC 8325 / PS 47)/ taxon id 93061

In [21]:
taxon_id = 93061
make_table(taxon_id)

,gene name,MCODE cluster,average shortest path length,cluster coefficient,closeness centrality
4,ABD29483.1,-,2.34,0.67,0.43
9,ABD30538.1,-,2.11,0.17,0.48
3,norB,Cluster 2,1.97,0.40,0.51
19,ABD29212.1,Cluster 3,1.92,0.71,0.52
14,spxA,-,1.84,0.46,0.54
33,rlmN,-,1.79,0.50,0.56
21,parE,Cluster 2,1.79,0.53,0.56
7,femA,Cluster 0,1.76,0.79,0.57
1,ABD30516.1,-,1.76,0.65,0.57
26,fosB,Cluster 3,1.74,0.53,0.58

- Escherichia coli (strain K12) / taxon id 83333

In [22]:
taxon_id = 83333
make_table(taxon_id)

,gene name,MCODE cluster,average shortest path length,cluster coefficient,closeness centrality
96,ydaC,-,2.78,0.33,0.36
88,ralR,-,2.66,0.33,0.38
89,blr,-,2.54,0.33,0.39
34,cof,-,2.47,0.00,0.41
91,pmrD,Cluster 4,2.46,0.90,0.41
95,eamA,-,2.39,0.60,0.42
94,yeaN,-,2.37,0.30,0.42
92,ydeI,-,2.26,0.38,0.44
101,ydeJ,-,2.24,0.40,0.45
50,yjjX,-,2.21,0.17,0.45

- Klebsiella pneumoniae subsp. pneumoniae (strain ATCC 700721 / MGH 78578) / taxon id 272620

In [23]:
taxon_id=272620
make_table(taxon_id)

,gene name,MCODE cluster,average shortest path length,cluster coefficient,closeness centrality
30,KPN_01053,-,3.81,0.00,0.26
31,marA,Cluster 4,2.84,0.33,0.35
32,marR,Cluster 4,2.34,0.33,0.43
27,acs,-,2.22,0.83,0.45
6,ycfV,-,2.16,0.50,0.46
20,wecC,Cluster 0,2.06,0.90,0.48
29,marB,Cluster 4,2.03,0.13,0.49
21,ybhT,-,1.97,0.47,0.51
28,aphA,-,1.91,0.48,0.52
2,uppS,Cluster 1,1.88,0.51,0.53